server:
    port: 8066
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/madhuprya/config-service-property
